using Microsoft.EntityFrameworkCore;
using RMDatabase;
using RMDatabase.Models;
using System.Globalization;

namespace Example
{
    class AddPerson
    {
        public void Execute()
        {
            using (var db = new DB())
            {
                var Pete = new Person
                {
                    Names = new List<Name>
                    {
                        new Name
                        {
                            Given = "Hanse",
                            Surname = "Huber",
                        },
                        new Name
                        {
                            Given = "Hanse",
                            IsPrimary = false,
                            NameType = NameTypes.Nickname
                        }
                    },
                    Living = true,
                    Sex = Sex.Male,
                    Note = "This person was generated by rmSharp",
                    ChangeDate = DateTime.Parse("1964-11-24"),
                };

                var Mary = new Person
                {
                    Names = new List<Name> { new Name { Given = "Maria", Surname = "Kaindl" } },
                    Sex = Sex.Female
                };

                var name = new Name();
                name.Given = "asdfaf";
                name.Surname = "asfasf";

                var child = new Person();
                child.Names.Add(name);

                var fam = new Family()
                {
                    Husband = Pete,
                    Wife = Mary,
                };



                db.Persons.Add(Pete);
                db.Persons.Add(Mary);
                db.Persons.Add(child);
                db.Families.Add(fam);
                var n = db.SaveChanges();
            }
        }
    }
}






