// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class AddressLinkTable
{
    public long LinkId { get; set; }

    public long? OwnerType { get; set; }

    public long? AddressId { get; set; }

    public long? OwnerId { get; set; }

    public long? AddressNum { get; set; }

    public string? Details { get; set; }

    public double? UtcmodDate { get; set; }
}