// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class CitationTable
{
    public long CitationId { get; set; }

    public long? SourceId { get; set; }

    public string? Comments { get; set; }

    public string? ActualText { get; set; }

    public string? RefNumber { get; set; }

    public string? Footnote { get; set; }

    public byte[]? ShortFootnote { get; set; }

    public string? Bibliography { get; set; }

    public byte[]? Fields { get; set; }

    public double? UtcmodDate { get; set; }

    public string? CitationName { get; set; }
}