// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class EventTable
{
    public long EventId { get; set; }

    public long? EventType { get; set; }

    public long? OwnerType { get; set; }

    public long? OwnerId { get; set; }

    public long? FamilyId { get; set; }

    public long? PlaceId { get; set; }

    public long? SiteId { get; set; }

    public string? Date { get; set; }

    public long? SortDate { get; set; }

    public long? IsPrimary { get; set; }

    public long? IsPrivate { get; set; }

    public long? Proof { get; set; }

    public long? Status { get; set; }

    public string? Sentence { get; set; }

    public string? Details { get; set; }

    public string? Note { get; set; }

    public double? UtcmodDate { get; set; }
}