// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class FactTypeTable
{
    public long FactTypeId { get; set; }

    public long? OwnerType { get; set; }

    public string? Name { get; set; }

    public string? Abbrev { get; set; }

    public string? GedcomTag { get; set; }

    public long? UseValue { get; set; }

    public long? UseDate { get; set; }

    public long? UsePlace { get; set; }

    public string? Sentence { get; set; }

    public long? Flags { get; set; }

    public double? UtcmodDate { get; set; }
}