// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class Family
{
    public long FamilyId { get; set; }

    public long FatherId { get; set; } 

    public long MotherId { get; set; }

    public long ChildId { get; set; }

    public long HusbOrder { get; set; }

    public long WifeOrder { get; set; }

    public bool IsPrivate { get; set; } = false;

    public long Proof { get; set; }

    public long SpouseLabel { get; set; }

    public long FatherLabel { get; set; }

    public long MotherLabel { get; set; }

    public string SpouseLabelStr { get; set; } = string.Empty;

    public string FatherLabelStr { get; set; } = string.Empty;

    public string MotherLabelStr { get; set; } = string.Empty;

    public string Note { get; set; } = string.Empty;

    public DateTime ChangeDate { get; set; } = DateTime.Now;

    virtual public ICollection<Person> Children { get; set; } = [];

    virtual public Person? Father { get; set; }
    virtual public Person? Mother { get; set; }
}