// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class FamilyTable
{
    public long FamilyId { get; set; }

    public long? FatherId { get; set; }

    public long? MotherId { get; set; }

    public long? ChildId { get; set; }

    public long? HusbOrder { get; set; }

    public long? WifeOrder { get; set; }

    public long? IsPrivate { get; set; }

    public long? Proof { get; set; }

    public long? SpouseLabel { get; set; }

    public long? FatherLabel { get; set; }

    public long? MotherLabel { get; set; }

    public string? SpouseLabelStr { get; set; }

    public string? FatherLabelStr { get; set; }

    public string? MotherLabelStr { get; set; }

    public string? Note { get; set; }

    public double? UtcmodDate { get; set; }
}