// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class GroupTable
{
    public long RecId { get; set; }

    public long? GroupId { get; set; }

    public long? StartId { get; set; }

    public long? EndId { get; set; }

    public double? UtcmodDate { get; set; }
}