// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class Medium
{
    public long MediaId { get; set; }

    public long? MediaType { get; set; }

    public string? MediaPath { get; set; }

    public string? MediaFile { get; set; }

    public string? Url { get; set; }

    public byte[]? Thumbnail { get; set; }

    public string? Caption { get; set; }

    public string? RefNumber { get; set; }

    public string? Date { get; set; }

    public long? SortDate { get; set; }

    public string? Description { get; set; }

    public double? UtcmodDate { get; set; }
}