// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class MediaLinkTable
{
    public long LinkId { get; set; }

    public long? MediaId { get; set; }

    public long? OwnerType { get; set; }

    public long? OwnerId { get; set; }

    public long? IsPrimary { get; set; }

    public long? Include1 { get; set; }

    public long? Include2 { get; set; }

    public long? Include3 { get; set; }

    public long? Include4 { get; set; }

    public long? SortOrder { get; set; }

    public long? RectLeft { get; set; }

    public long? RectTop { get; set; }

    public long? RectRight { get; set; }

    public long? RectBottom { get; set; }

    public string? Comments { get; set; }

    public double? UtcmodDate { get; set; }
}