// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class NameTable
{
    public long NameId { get; set; }

    public long? OwnerId { get; set; }

    public string? Surname { get; set; }

    public string? Given { get; set; }

    public string? Prefix { get; set; }

    public string? Suffix { get; set; }

    public string? Nickname { get; set; }

    public long? NameType { get; set; }

    public string? Date { get; set; }

    public long? SortDate { get; set; }

    public long? IsPrimary { get; set; }

    public long? IsPrivate { get; set; }

    public long? Proof { get; set; }

    public string? Sentence { get; set; }

    public string? Note { get; set; }

    public long? BirthYear { get; set; }

    public long? DeathYear { get; set; }

    public long? Display { get; set; }

    public string? Language { get; set; }

    public double? UtcmodDate { get; set; }

    public string? SurnameMp { get; set; }

    public string? GivenMp { get; set; }

    public string? NicknameMp { get; set; }
}