// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DelegateDecompiler;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RMDatabase.Models;

public partial class Person
{
    public long PersonId { get; set; }

    public string? UniqueId { get; set; }

    public long? Sex { get; set; }

    public long ParentId { get; set; }

    public long SpouseId { get; set; }

    public long Color { get; set; }

    public long Color1 { get; set; }

    public long Color2 { get; set; }

    public long Color3 { get; set; }

    public long Color4 { get; set; }

    public long Color5 { get; set; }

    public long Color6 { get; set; }

    public long Color7 { get; set; }

    public long Color8 { get; set; }

    public long Color9 { get; set; }

    public long Relate1 { get; set; }

    public long Relate2 { get; set; }

    public long Flags { get; set; }

    public long Living { get; set; }

    public bool IsPrivate { get; set; }

    public long Proof { get; set; }

    public long? Bookmark { get; set; }

    public string? Note { get; set; }

    public double UtcmodDate { get; set; }

    [Decompile]
    public Name PrimaryName => Names.First(n => n.NameType == NameTypes.Primary);
   

    public virtual ICollection<Family> Families { get; set; } = [];

    public virtual ICollection<Name> Names { get; set; } = [];
    public virtual ICollection<Address> Addresses { get; set; } = [];
}