// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class SourceTemplateTable
{
    public long TemplateId { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public long? Favorite { get; set; }

    public string? Category { get; set; }

    public string? Footnote { get; set; }

    public string? ShortFootnote { get; set; }

    public string? Bibliography { get; set; }

    public byte[]? FieldDefs { get; set; }

    public double? UtcmodDate { get; set; }
}