// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class Source
{
    public long SourceId { get; set; }

    public string? Name { get; set; }

    public string? RefNumber { get; set; }

    public string? ActualText { get; set; }

    public string? Comments { get; set; }

    public long? IsPrivate { get; set; }

    public long? TemplateId { get; set; }

    public byte[]? Fields { get; set; }

    public double? UtcmodDate { get; set; }
}