// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class TagTable
{
    public long TagId { get; set; }

    public long? TagType { get; set; }

    public long? TagValue { get; set; }

    public string? TagName { get; set; }

    public string? Description { get; set; }

    public double? UtcmodDate { get; set; }
}