// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class Urltable
{
    public long LinkId { get; set; }

    public long? OwnerType { get; set; }

    public long? OwnerId { get; set; }

    public long? LinkType { get; set; }

    public string? Name { get; set; }

    public string? Url { get; set; }

    public string? Note { get; set; }

    public double? UtcmodDate { get; set; }
}