// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RMDatabase.Models;

public partial class WitnessTable
{
    public long WitnessId { get; set; }

    public long? EventId { get; set; }

    public long? PersonId { get; set; }

    public long? WitnessOrder { get; set; }

    public long? Role { get; set; }

    public string? Sentence { get; set; }

    public string? Note { get; set; }

    public string? Given { get; set; }

    public string? Surname { get; set; }

    public string? Prefix { get; set; }

    public string? Suffix { get; set; }

    public double? UtcmodDate { get; set; }
}