// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace rmtester.Models;

public partial class Family
{
    public long Id { get; set; }

    public long? FatherId { get; set; }

    public long? MotherId { get; set; }
}