// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace rmtester.Models;

public partial class Person
{
    public long Id { get; set; }

    public string Name { get; set; }
}